### ISSUE TITLE
No module named 'vtkmodules'

### ISSUE THREAD

**Issue by ulibuck** [imirzov/ccx2paraview#23]
Hi,
I installed the binary for Linux, also installed vtk and numpy from my package manager but get the following ModuleNotFoundError

`Traceback (most recent call last):
  File "/media/ihor/WORK/Calculix/ccx2paraview/ccx2paraview/__init__.py", line 21, in <module>
  File "/media/ihor/WORK/Calculix/ccx2paraview/ccx2paraview/writer.py", line 14, in <module writer>
  File "/home/ihor/.local/lib/python3.8/site-packages/vtk.py", line 30, in <module vtk>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'vtkmodules'`

I am on Linux Mint Cinnamon 20.2 and cannot work out what is missing.
Would appreciate any hint.

**Comment by ulibuck** [comment]
Hi
I figured it out: installed vtk from pip3. Now it works.
Thanks
