### ISSUE TITLE
frd to vtu conversion issue with vtk module

### ISSUE THREAD

**Issue by jssrivathsa** [imirzov/ccx2paraview#42]
I am facing this error after compiling the ccx2paraview
in Ubuntu 22.04, python 3.9, 

Error--------------------------------------
Traceback (most recent call last):
  File "/home/sjagalur1980/CalculiX/ccx2paraview-3.0.0/ccx2paraview/__main__.py", line 2, in <module>
    import cli
  File "/home/sjagalur1980/CalculiX/ccx2paraview-3.0.0/ccx2paraview/cli.py", line 13, in <module cli>
    from common import Converter
  File "/home/sjagalur1980/CalculiX/ccx2paraview-3.0.0/ccx2paraview/common.py", line 21, in <module common>
    import vtk
  File "/home/sjagalur1980/anaconda3/envs/sjrpy39/lib/python3.9/site-packages/vtk.py", line 47, in <module vtk>
    from vtkmodules.vtkRenderingMatplotlib import *
ImportError: /home/sjagalur1980/anaconda3/envs/sjrpy39/lib/python3.9/site-packages/vtkmodules/libvtkPythonInterpreter-9.3.so: undefined symbol: Py_RunMain

**Comment by imirzov** [comment]
Hi.
From provided log I see that there is some problem between vtk library and python version you're using. Python 3.9 is quite old. Moreover I've never been using ccx2paraview with anaconda.

**Comment by jssrivathsa** [comment]
thanks for the input. I was able to use directly running the python from the ccx2paraview 3.0.0. But it creates many vtu files. Can we merge all vtu to one file somehow?

**Comment by imirzov** [comment]
No, ccx2paraview does not provide such a possibility. See caution about it in the README:
https://github.com/calculix/ccx2paraview?tab=readme-ov-file#calculix-to-paraview-converter-frd-to-vtkvtu
"""If you have 300 time steps in the FRD, there will be 300 Paraview files. If you need one file - write output only for one step in your CalculiX model."""
